### ISSUE TITLE
dev-lang/mono-4.9.0.729 compilation bug, random.

### ISSUE THREAD

**Issue by dorvan** [gentoo/dotnet#270] opened 2016-11-23 13:56 UTC
hello Mr!
an extract of log:

MCS     [build] System.Reflection.Extensions.dll
MCS     [build] mcs.exe
AOT     [build] mscorlib.dll.so
AOT     [build] mcs.exe.so
ld: /ports/tmp/portage/dev-lang/mono-4.9.0.729/temp/mono_aot_CvuBZU.o: relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
ld: final link failed: Nonrepresentable section on output
AOT of image ./../../class/lib/build/mcs.exe failed.
Mono Ahead of Time compiler - compiling assembly /ports/tmp/portage/dev-lang/mono-4.9.0.729/work/mono-4.9.0-abi_x86_32.x86/mcs/class/lib/build/mcs.exe
AOTID 6A019F50-0DEE-6224-C09C-4868DC37B38A
Code: 4418992(59%) Info: 126616(1%) Ex Info: 2560845(34%) Unwind Info: 80(0%) Class Info: 66165(0%) PLT: 6789(0%) GOT Info: 153971(2%) Offsets: 95065(1%) GOT: 62012
Compiled: 21429/21429 (100%), No GOT slots: 12498 (58%), Direct calls: 23662 (110%)
Executing the native assembler: "as"   -o /ports/tmp/portage/dev-lang/mono-4.9.0.729/temp/mono_aot_CvuBZU.o /ports/tmp/portage/dev-lang/mono-4.9.0.729/temp/mono_aot_CvuBZU
Executing the native linker: "ld"  -shared -o ./../../class/lib/build//mcs.exe.so.tmp  /ports/tmp/portage/dev-lang/mono-4.9.0.729/temp/mono_aot_CvuBZU.o
ld: /ports/tmp/portage/dev-lang/mono-4.9.0.729/temp/mono_aot_253bF6.o: relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
ld: final link failed: Nonrepresentable section on output
AOT of image ./../../class/lib/build//mscorlib.dll failed.
Mono Ahead of Time compiler - compiling assembly /ports/tmp/portage/dev-lang/mono-4.9.0.729/work/mono-4.9.0-abi_x86_32.x86/mcs/class/lib/build/mscorlib.dll
AOTID 58185B37-1C6B-94B6-EDC5-D2D18022AB34
Code: 5027572(58%) Info: 140277(1%) Ex Info: 3028892(35%) Unwind Info: 80(0%) Class Info: 102424(1%) PLT: 8077(0%) GOT Info: 174556(2%) Offsets: 121416(1%) GOT: 69044
Compiled: 26661/26738 (99%), No GOT slots: 17254 (64%), Direct calls: 41774 (70%)
75 methods have other problems (0%)
Executing the native assembler: "as"   -o /ports/tmp/portage/dev-lang/mono-4.9.0.729/temp/mono_aot_253bF6.o /ports/tmp/portage/dev-lang/mono-4.9.0.729/temp/mono_aot_253bF6
Executing the native linker: "ld"  -shared -o /ports/tmp/portage/dev-lang/mono-4.9.0.729/work/mono-4.9.0-abi_x86_32.x86/mcs/class/lib/build/mscorlib.dll.so.tmp  /ports/tmp/portage/dev-lang/mono-4.9.0.729/temp/mono_aot_253bF6.o
make[7]: *** [Makefile:36: ../../class/lib/build//mscorlib.dll.so] Error 1
make[6]: *** [../../build/rules.make:198: do-all] Error 2
make[5]: *** [build/rules.make:225: all-recursive] Error 1
make[4]: *** [Makefile:49: profile-do--build--all] Error 2
make[3]: *** [Makefile:45: profiles-do--all] Error 2
make[2]: *** [Makefile:560: all-local] Error 2
make[2]: Leaving directory '/ports/tmp/portage/dev-lang/mono-4.9.0.729/work/mono-4.9.0-abi_x86_32.x86/runtime'
make[1]: *** [Makefile:525: all-recursive] Error 1
make[1]: Leaving directory '/ports/tmp/portage/dev-lang/mono-4.9.0.729/work/mono-4.9.0-abi_x86_32.x86'
make: *** [Makefile:454: all] Error 2
 * ERROR: dev-lang/mono-4.9.0.729::gentoo failed (compile phase):
 *   emake failed
 *
 * If you need support, post the output of `emerge --info '=dev-lang/mono-4.9.0.729::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-lang/mono-4.9.0.729::gentoo'`.
 * The complete build log is located at '/ports/tmp/portage/dev-lang/mono-4.9.0.729/temp/build.log'.
 * The ebuild environment file is located at '/ports/tmp/portage/dev-lang/mono-4.9.0.729/temp/environment'.
 * Working directory: '/ports/tmp/portage/dev-lang/mono-4.9.0.729/work/mono-4.9.0-abi_x86_32.x86'
 * S: '/ports/tmp/portage/dev-lang/mono-4.9.0.729/work/mono-4.9.0'

**Comment by ArsenShnurkov** [comment] 2016-11-23 18:41
I don't understand how mono builds. That deep knowledge lost with creators who left us.
The only idea is to try to add <a href="http://stackoverflow.com/questions/5311515/gcc-fpic-option">-fPIC</a> into <a href="https://en.wikipedia.org/wiki/CFLAGS">CFLAGS/CXXFLAGS</a> variables of this package (<a href="https://wiki.gentoo.org/wiki//etc/portage/package.env">/etc/portage/package.env</a>)

**Comment by mpkh** [comment] 2016-11-23 18:44
@dorvan can you reproduce this on older versions or only this one is corrupted?

**Comment by mpkh** [comment] 2016-11-25 11:56
@dorvan seems to be an issue with binutils-2.27

**Comment by piedar** [comment] 2016-11-25 21:09
@mpkh I'm confused how mono 4.9.0 was added in the first place, considering that [4.8.0](http://www.mono-project.com/docs/about-mono/releases/4.8.0/) is still a preview release.

**Comment by dorvan** [comment] 2016-11-26 09:24
@mpkh i confirm it's related to binutils-2.27, only mono-4.9.0 and grub2-beta3 are afflicted,

**Comment by dorvan** [comment] 2016-11-26 09:26
@ArsenShnurkov consider the dep with binutils-2.27, the workaround works? (really..)

**Comment by mpkh** [comment] 2016-11-26 18:39
I'm not sure at the moment about correct fix. Suggestions are very welcome.

**Comment by mpkh** [comment] 2016-12-01 06:50
@piedar note, I've downgraded nightly to recent release recently but I still need help with binutils

**Comment by mpkh** [comment] 2016-12-02 09:14
should be fixed https://bugs.gentoo.org/show_bug.cgi?id=600664

**Closed by mpkh** 2016-12-02 09:14 UTC
Labels: bug
